# å…¬å…±é…ç½®
common:
  ecsHost: "http://47.99.200.185/"
  tempPath: "./cache/wechat"
  # å¾®ä¿¡å…¬ä¼—å·çš„openID
  fromOpenid: gh_eeaaf5c9001c

  # ç”¨æˆ·è®¢é˜…å…¬ä¼—å·åï¼Œè§¦å‘çš„è‡ªåŠ¨å›å¤ä¸­çš„ä¿¡æ¯
  welcome:
    title: æ¬¢è¿å…³æ³¨è¿™ä¸ªè¶…æ­£ç»çš„å…¬ä¼—å·~
    # ç”¨æˆ·å…³æ³¨å…¬ä¼—å·åï¼Œè§¦å‘è‡ªåŠ¨å›å¤ï¼Œä¼šå›å¤ä¸€æ¡å›¾æ–‡æ¶ˆæ¯ï¼Œä¸‹é¢æ˜¯å›¾æ–‡æ¶ˆæ¯çš„å›¾ç‰‡
    banner: ${common.escHost}static/imgs/banner/welcome_news_banner.jpg
    description: "æˆ‘çœ‹è§ï¼Œä½ ä»äººç¾¤ä¸­èµ°æ¥...\n\nç‚¹å‡»æŸ¥çœ‹å…¨æ–‡"
    url: http://note.youdao.com/noteshare?id=3df33d89adae7e91dbdf697eb88d3075&sub=E889E1B585C84DF08D25D4B1CE654823

  # å…¨å±€å¸®åŠ©ä¿¡æ¯
  help:
    errorMsg: æœåŠ¡å™¨å‡ºç°äº†ä¸€ç‚¹å°æ•…éšœï¼Œå¯ä»¥è¶æœºæ’©æ’©ä¼¦å“¥^_^~${menu.commonCmd}
    commonMsg: Hey!æ‚¨çš„æ¶ˆæ¯æˆ‘å·²ç»æ”¶åˆ°å•¦ï¼~æ‚¨å¯ä»¥å›å¤åŠŸèƒ½åˆ—è¡¨å‰çš„ä»£ç ï¼Œä½¿ç”¨ç›¸åº”çš„åŠŸèƒ½å“¦~
    rootMsg: å·²ä¸ºå½“å‰ç”¨æˆ·å¼€å¯rootæƒé™ï¼Œæ‚¨å¯ä»¥è¿›è¡Œä½¿ç”¨ç›¸å…³ç®¡ç†å‘˜åŠŸèƒ½ï¼Œ5åˆ†ç§å†…æœ‰æ•ˆï¼
    permissionErrorMsg: æƒé™ä¸è¶³ï¼ä¸èƒ½æ‰§è¡ŒæŒ‡å®šå‘½ä»¤ã€‚è‹¥è¦ä½¿ç”¨ç›¸å…³åŠŸèƒ½ï¼Œè¯·ä¸»åŠ¨æ’©ä¼¦å“¥è·å–ROOTæƒé™ï¼${menu.commonCmd}

  menu:
    headerInfo: æ‚¨å¯ä»¥å›å¤å‰é¢çš„æ•°å­—ä½¿ç”¨ç›¸å…³çš„åŠŸèƒ½å“¦~
    commonCmd: "\n\næ‚¨è¿˜å¯ä»¥ä½¿ç”¨ä»¥ä¸‹ç‰¹æ®Šå‘½ä»¤ï¼š\n-ï¼šè¿”å›ä¸Šçº§èœå•\n#ï¼šè¿”å›é¦–é¡µ"

  # å›¾ç‰‡æ¶ˆæ¯æç¤ºä¿¡æ¯
  img:
    readyInfo: æ‚¨å¯ä»¥å‘æˆ‘å‘é€ä¸€å¼ éœ€è¦è½¬æ¢çš„å›¾ç‰‡å“¦~å›¾ç‰‡ç­‰å¾…çŠ¶æ€æŒç»­ä¸¤åˆ†é’Ÿ~
    errorMsg: å˜¿ï¼Œæ‚¨çš„å›¾ç‰‡æˆ‘å·²ç»æ”¶åˆ°ï¼Œä½†æ‚¨æœªæŒ‡å®šéœ€è¦è¿›è¡Œçš„æ“ä½œæˆ–å‘½ä»¤å·²è¿‡æœŸå“¦ï¼æ‚¨å¯ä»¥å…ˆæ ¹æ®èœå•ï¼Œé€‰å®šæ‚¨éœ€è¦çš„æ“ä½œåï¼Œå†å°†å›¾ç‰‡å‘é€ç»™æˆ‘ï¼Œæˆ‘å°†æŒ‰ç…§æ‚¨æŒ‡å®šçš„æ“ä½œï¼Œå¯¹å›¾ç‰‡è¿›è¡Œå¤„ç†å“¦~


# å¾®ä¿¡ç›¸å…³é…ç½®
wechat:
  # ç”¨äºæœåŠ¡å™¨æ ¡éªŒç”¨çš„token
  token: lovebluesky
  # åŸºç¡€æ¥å…¥åŸŸå
  baseUrl: "https://api.weixin.qq.com"
  # appid and secret
  appid: wxa68659fde8555471
  secret: 73f2796ecf1d04d6136b4b41eb603f3b
  # è·å– access_token é“¾æ¥
  accessTokenUrl: ${wechat.baseUrl}/cgi-bin/token?grant_type=client_credential&appid=${wechat.appid}&secret=${wechat.secret}
  # è·å– å¾®ä¿¡æœåŠ¡å™¨ IPåœ°å€
  ipUrl: ${wechat.baseUrl}/cgi-bin/getcallbackip?access_token=


# æ–‡ç« å‘½ä»¤ç›¸å…³é…ç½®
article:
  imgBaseUrl: ${common.escHost}static/imgs/articles/article_{}.jpg
  addInfo: "æ‚¨å¯ä»¥å›å¤ã€url|wdxpn|urlã€‘ï¼Œä½¿ç”¨ã€|wdxpn|ã€‘å°†URLåˆ†éš”å¼€~${menu.commonCmd}"
  youdaoUrl: https://note.youdao.com/yws/public/note/{}?editorType=0


# è€é»„å†ç›¸å…³é…ç½®
almanac:
  url: "http://m.laohuangli.net/"
  luckyImgUrl: ${common.escHost}static/imgs/almanac/luck_lucky.jpg
  restImgUrl: ${common.escHost}static/imgs/almanac/luck_rest.jpg
  errorInfo: è·å–é»„å†ä¿¡æ¯å¤±è´¥ï¼Œè¯·ç¨åé‡è¯•~


# å…¬äº¤æŸ¥è¯¢ç›¸å…³é…ç½®
bus:
  icon: ğŸšŒ


# å›¾ç‰‡è½¬å­—ç¬¦ä¸²ï¼Œç›¸å…³é…ç½®
toys:
  name: å¼ ä¸‰
  img2txt:
    elements: "@#&$%*o!;\u0020"
    tempPath: ${common.tempPath}imgs/{openid}/{current}.jpg
    resultInfoHeader: æ‚¨å¯ä»¥ç‚¹å‡»ä¸‹é¢çš„é“¾æ¥ï¼Œä¸‹è½½è½¬æ¢åçš„å›¾ç‰‡å“¦~æ‰€æœ‰ä¸‹è½½é“¾æ¥30åˆ†é’Ÿå†…æœ‰æ•ˆï¼
    resultBaseUrl: ${common.escHost}temp/wechat/imgs/{openid}/{filename}